import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedMenorDe2a12aosWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedInfanteMenora2aosWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedAppBarNavigationWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedBuscarWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedProgramatuviajeWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedAdultoMayorde13aosWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedviajewidget/generated/GeneratedGroup7Widget.dart';

/* Frame Viaje
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedViajeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 188.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedVectorWidget2(),
              ),
              Positioned(
                left: 276.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 20.45462989807129,
                height: 15.0,
                child: GeneratedVectorWidget3(),
              ),
              Positioned(
                left: 70.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 32.0,
                child: GeneratedAdultoMayorde13aosWidget(),
              ),
              Positioned(
                left: 70.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 32.0,
                child: GeneratedMenorDe2a12aosWidget(),
              ),
              Positioned(
                left: 70.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 32.0,
                child: GeneratedInfanteMenora2aosWidget(),
              ),
              Positioned(
                left: 198.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 50.0,
                child: GeneratedBuscarWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAppBarNavigationWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 5.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 30.0,
                child: GeneratedProgramatuviajeWidget(),
              )
            ]),
      ),
    ));
  }
}
