import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedpersonoutlinewidget1/generated/GeneratedVectorWidget72.dart';
import 'package:flutterapp/centralcamioneraapp/generatedpersonoutlinewidget1/generated/GeneratedVectorWidget73.dart';

/* Frame person-outline
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPersonoutlineWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 512.0,
        height: 512.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 167.7179412841797,
                top: 48.0,
                right: null,
                bottom: null,
                width: 176.56411743164062,
                height: 192.0,
                child: GeneratedVectorWidget72(),
              ),
              Positioned(
                left: 63.9975700378418,
                top: 304.0,
                right: null,
                bottom: null,
                width: 384.01483154296875,
                height: 160.0,
                child: GeneratedVectorWidget73(),
              )
            ]),
      ),
    ));
  }
}
