import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedhomewidget/generated/GeneratedVectorWidget76.dart';
import 'package:flutterapp/centralcamioneraapp/generatedhomewidget/generated/GeneratedVectorWidget77.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 512.0,
        height: 512.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 63.900001525878906,
                top: 99.06092834472656,
                right: null,
                bottom: null,
                width: 384.1600036621094,
                height: 380.9390869140625,
                child: GeneratedVectorWidget76(),
              ),
              Positioned(
                left: 15.999621391296387,
                top: 32.0,
                right: null,
                bottom: null,
                width: 480.0011901855469,
                height: 240.0237579345703,
                child: GeneratedVectorWidget77(),
              )
            ]),
      ),
    ));
  }
}
