import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedCulessonlosdestinosyorgenesdeOmnibusdeMxicoWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedAppBarNavigationWidget2.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedPreguntasFrecuentesWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedOmni1Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedLosdestinosprincipalesdeOmnibusdeMxicosonCiudaddeMxicoA.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 593.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAppBarNavigationWidget2(),
              ),
              Positioned(
                left: 2.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 5.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 177.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: -2.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 157.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 30.0,
                child: GeneratedPreguntasFrecuentesWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 45.0,
                child:
                    GeneratedLosdestinosprincipalesdeOmnibusdeMxicosonCiudaddeMxicoA(),
              ),
              Positioned(
                left: 24.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 19.0,
                child:
                    GeneratedCulessonlosdestinosyorgenesdeOmnibusdeMxicoWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 207.0,
                child: GeneratedOmni1Widget(),
              )
            ]),
      ),
    ));
  }
}
