import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedloginwidget/generated/GeneratedXhCgWvSHUJUWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedloginwidget/generated/GeneratedOmnibus_de_mexico1Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedloginwidget/generated/GeneratedDatosWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 238, 238, 238),
                ),
              ),
              Positioned(
                left: -77.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 513.0,
                height: 640.0,
                child: GeneratedXhCgWvSHUJUWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 278.0,
                child: GeneratedDatosWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 83.0,
                child: GeneratedOmnibus_de_mexico1Widget(),
              )
            ]),
      ),
    ));
  }
}
