import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedConfiguracinWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedSettingsoutlineWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedRectangle17Widget4.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedLockclosedoutlineWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedAppBarNavigationWidget5.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGlobeoutlineWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedLocationoutlineWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedShieldoutlineWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedajusteswidget/generated/GeneratedPersonoutlineWidget.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle17Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAppBarNavigationWidget5(),
              ),
              Positioned(
                left: 303.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 5.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 33.0,
                child: GeneratedConfiguracinWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedPersonoutlineWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSettingsoutlineWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedLockclosedoutlineWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedLocationoutlineWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGlobeoutlineWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedShieldoutlineWidget(),
              )
            ]),
      ),
    ));
  }
}
