import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedVectorWidget70.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedVectorWidget68.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedLine6Widget6.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedLine5Widget6.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedVectorWidget66.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedVectorWidget71.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedRectangle18Widget6.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedLine7Widget6.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedLine4Widget6.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedVectorWidget67.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedLine3Widget6.dart';
import 'package:flutterapp/centralcamioneraapp/generatedappbarnavigationwidget6/generated/GeneratedVectorWidget69.dart';

/* Component AppBarNavigation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppBarNavigationWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 50.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 50.0,
              child: GeneratedRectangle18Widget6(),
            ),
            Positioned(
              left: 60.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 1.0,
              child: GeneratedLine3Widget6(),
            ),
            Positioned(
              left: 179.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 1.0,
              child: GeneratedLine5Widget6(),
            ),
            Positioned(
              left: 240.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 1.0,
              child: GeneratedLine6Widget6(),
            ),
            Positioned(
              left: 300.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 1.0,
              child: GeneratedLine7Widget6(),
            ),
            Positioned(
              left: 120.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 1.0,
              child: GeneratedLine4Widget6(),
            ),
            Positioned(
              left: 200.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 21.429370880126953,
              height: 30.0,
              child: GeneratedVectorWidget66(),
            ),
            Positioned(
              left: 256.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 27.857746124267578,
              height: 30.0,
              child: GeneratedVectorWidget67(),
            ),
            Positioned(
              left: 136.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 25.714284896850586,
              height: 30.0,
              child: GeneratedVectorWidget68(),
            ),
            Positioned(
              left: 13.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 34.28571319580078,
              height: 30.0,
              child: GeneratedVectorWidget69(),
            ),
            Positioned(
              left: 316.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 29.214859008789062,
              height: 30.0,
              child: GeneratedVectorWidget70(),
            ),
            Positioned(
              left: 75.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 30.000097274780273,
              height: 30.0,
              child: GeneratedVectorWidget71(),
            )
          ]),
    ));
  }
}
