import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedCascada1Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedLugaresparavisitarWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedAppBarNavigationWidget3.dart';
import 'package:flutterapp/centralcamioneraapp/generatedlugareswidget/generated/GeneratedGroup13Widget.dart';

/* Frame Lugares
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLugaresWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAppBarNavigationWidget3(),
              ),
              Positioned(
                left: 182.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 5.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 30.0,
                child: GeneratedLugaresparavisitarWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 246.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 246.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 157.1999969482422,
                child: GeneratedCascada1Widget(),
              )
            ]),
      ),
    ));
  }
}
