import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedAlanReynaldoRoblesSotoWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedRectangle16Widget4.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedAppBarNavigationWidget4.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedPERFILVACIO1Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedperfilwidget/generated/GeneratedCdJuarezChihuahuaEdad17aosViajeshechos14Ciudadmasvisita.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle16Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAppBarNavigationWidget4(),
              ),
              Positioned(
                left: 243.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 5.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 484.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 150.0,
                child: GeneratedPERFILVACIO1Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 341.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 25.0,
                child: GeneratedAlanReynaldoRoblesSotoWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 220.0,
                child:
                    GeneratedCdJuarezChihuahuaEdad17aosViajeshechos14Ciudadmasvisita(),
              )
            ]),
      ),
    ));
  }
}
