import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedBoletosbaratosWidget1.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedAppBarNavigationWidget1.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget/generated/GeneratedRectangle20Widget.dart';

/* Frame Boletos baratos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBoletosbaratosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 30.0,
                child: GeneratedBoletosbaratosWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAppBarNavigationWidget1(),
              ),
              Positioned(
                left: 123.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 5.0,
                child: GeneratedRectangle20Widget(),
              )
            ]),
      ),
    ));
  }
}
